### ISSUE TITLE
String "[[loginusing]]" appears on login form

### ISSUE THREAD

**Issue by leonstr** [pitbulk/moodle_saml#12]
The login page in login.php appears to reproduce the older 2.x login form. But this was revised in Moodle 2.6 and the "loginusing" string is no longer defined in the language files. So you end up with a form with "[[loginusing]]" above the username and password fields when this plugin is enabled with versions 2.6 or above.

**Comment by pitbulk** [comment]
Do you have a Pull Request for that?

**Comment by leonstr** [comment]
I'm afraid not.

**Comment by pitbulk** [comment]
Fixed on new release.
