### ISSUE TITLE
saml_config.json in web-root, instead of data-root

### ISSUE THREAD

**Issue by henrikthorn** [pitbulk/moodle_saml#13]
When saving settings in the auth/saml module, users will get a warning with a permission denied when trying to write the config to the saml_config.json file in the plugin-root. Instead this file should be saved in Moodledata, allowing the webserver to write to the file. Furthermore this error will make the plugin fail on clustered setup, since the file has to be saved on each frontend, hence the placement of the config file.

**Comment by pitbulk** [comment]
Nice suggestion.

**Comment by henrikthorn** [comment]
I'll create one :-)

**Comment by pitbulk** [comment]
any progress?

**Comment by henrikthorn** [comment]
I've done some of the changes, but haven't been able to test it well enough yet.

**Comment by hcpss-banderson** [comment]
@henrikthorn and @pitbulk, I am anxious for this improvement. Since it's been a few months since this had activity, I am planning on submitting a pull request of my own. I'm going to try to incorporate your pull request #14 if I can.

**Comment by pitbulk** [comment]
Thanks.

**Comment by hcpss-banderson** [comment]
Continuing work on this at #27.

**Comment by pitbulk** [comment]
Fixed on new release.
