### ISSUE TITLE
wantsurl is deleted when returning from SAML-auth

### ISSUE THREAD

**Issue by henrikthorn** [pitbulk/moodle_saml#16]
In index.php we do not use Moodle-sessions since this fucks Simplesamls session handling up. However, since we're not using sessions we loose the info about where the user should be redirected after the login has been completed, since this is part of $SESSION->wantsurl. 

A solution is to change session-store for simplesamlphp, so it uses either memcache or sql - but it would be nice if we could figure a way to redirect users to the correct place, without requiring users to setup simplesaml. 

I've tried different approaches, but nothing has worked out so far.

**Comment by pitbulk** [comment]
I had a lot of conflicts with the session stuff.

That is why I created a new SAML plugin that uses other SAML library instead of simpleSAMLphp: https://github.com/pitbulk/moodle-onelogin

**Comment by pitbulk** [comment]
I tested and is working for me.
