### ISSUE TITLE
Plugin update - Unprefixed functions

### ISSUE THREAD

**Issue by foxwill** [pitbulk/moodle_saml#17]
We have received a request from Moodle to upgrade the plugin to support their guidelines, I'm opening several issues here to track getting these adjusted:

Major Issues
Below is a list of major code issues and concerns that prevent the plug-in from passing the
Code Certification Process.
*3.1 CODE CHANGE ISSUES:*
**3.1.1 Unprefixed functions included.**
• Description: Functions in use in the Moodle system should have either a
namespace, or prefixes that prevent fatal namespace collisions.
• Example(s):
o File: **functions.php**
o function **deleteLocalSession() {**
function **logoutpage_hook() {**
 function **get_saml_settings() {**
• Suggested Fix: Append **auth_onelogin_saml_prefix** (to match the other
functions in that file) and change all instances of the functions elsewhere
then retest the plugin.
• Reason for Fix: Namespace collisions

**Comment by pitbulk** [comment]
Fixed on new release.
