### ISSUE TITLE
Plugin Update - Moodle Global Variables

### ISSUE THREAD

**Issue by foxwill** [pitbulk/moodle_saml#18]
We have received a request from Moodle to upgrade the plugin to support their guidelines, I'm opening several issues here to track getting these adjusted:

3.1.2 Use the proper Moodle global variables.
• Description: Keeps with Moodle coding guidelines.
• Example(s):
o File: auth.php, index.php
o auth.php 37: 
require_once($GLOBALS['CFG']-
>libdir.'/authlib.php'); 39:
require_once($GLOBALS['CFG']->
libdir.'\authlib.php'); 69: if
(isset($GLOBALS['onelogin_saml_login_attributes'])) { 
83: $saml_attributes =$GLOBALS['onelogin_saml_login_attributes'];
84: $nameID =$GLOBALS['onelogin_saml_nameID'];
153:$saml_attributes = $GLOBALS['onelogin_saml_login_attributes'];
235:$GLOBALS['CFG']->nolastloggedin = true;
238:$init_sso_url = $GLOBALS['CFG']-
>wwwroot.'/auth/onelogin_saml/index.php';
246: $logout_url = $GLOBALS['CFG']-
>wwwroot.'/auth/onelogin_saml/index.php?logo
ut=1'; index.php 134:
$GLOBALS['onelogin_saml_nameID'] =
$onelogin_saml_nameId = $auth->getNameId();
135:
$GLOBALS['onelogin_saml_login_attributes'] =
$saml_attributes = $auth->getAttributes();
158: $GLOBALS['onelogin_saml_login'] = TRUE;

• Suggested Fix: **See REF: Core global variables in Moodle are identified
using uppercase variables (ie $CFG, $SESSION, $USER, $COURSE,
$SITE, $PAGE, $DB and $THEME).**
• Reason for Fix: Coding guidelines
(https://docs.moodle.org/dev/Coding_style)

**Comment by pitbulk** [comment]
Hi @foxwill, thanks for creating those issues to improve and keep the plugin more compatible.

Right now I don't have enough time to fix all the issues you reported.
Can you create PRs to fix them?
