### ISSUE TITLE
Faster login process with new moodle api pre_loginpage_hook

### ISSUE THREAD

**Issue by brendanheywood** [pitbulk/moodle_saml#21]
There is a new api hook in moodle to avoid 2 extra redirects in the whole saml auth flow which can make login dramatically quicker.

See this moodle tracker:
https://tracker.moodle.org/browse/MDL-48887

API docs:
https://docs.moodle.org/dev/Authentication_plugins#pre_loginpage_hook.28.29

A working example (from a forked version of the saml auth plugin):
https://github.com/brendanheywood/moodle-auth_saml/commit/b6b11b964f1894ca322f6beb9d4dfde7e609e7c6

**Comment by pitbulk** [comment]
Fixed on new release.
