### ISSUE TITLE
auth/saml/login.php complains of missing $frm

### ISSUE THREAD

**Issue by hcpss-banderson** [pitbulk/moodle_saml#26]
When you turn on error display, there are warning s that $frm is not defined:

Notice:  Trying to get property of non-object in /vagrant/auth/saml/login.php on line 101
Notice: Trying to get property of non-object in /vagrant/auth/saml/login.php on line 113
Notice: Undefined variable: frm in /vagrant/auth/saml/login.php on line 112

**Comment by pitbulk** [comment]
Fixed on new release.
