### ISSUE TITLE
index.php loads saml config from plugin directory instead of dataroot

### ISSUE THREAD

**Issue by hcpss-banderson** [pitbulk/moodle_saml#30]
To test this:
1. Make sure you have a good saml_config.php in dataroot
2. Edit saml_config.php and change the sp source to "foobar"
3. Try to log in

You will see the error:
Invalid authentication source: foobar

The expected behavior is that <moodle>/auth/saml/saml_config.php should be ignored if <dataroot>/saml_config.php exists.

I think this is because index.php line 13 is accessing $CFG->dataroot, but config.php has not been included. Adding "require_once('../../config.php');" to the top of the file should fix it.

**Comment by pitbulk** [comment]
Now I remember why I saved the saml_config.php in the root of the saml plugin folder.
I wanted to avoid the load of the moodle config file in order to avoid session conflicts :( .

**Comment by pitbulk** [comment]
Fixed at https://github.com/pitbulk/moodle_saml/commit/b3aee0bdee93b9e9800d641e0d00923310ca5a47
