### ISSUE TITLE
The enrolment plugin 'saml' should override the function can_hide_show_instance()

### ISSUE THREAD

**Issue by rezaies** [pitbulk/moodle_saml#38]
Using Moodle 2.9 got the following error:

The enrolment plugin 'saml' should override the function can_hide_show_instance().
- line 1571 of /lib/enrollib.php: call to debugging()
- line 249 of /enrol/instances.php: call to enrol_plugin->can_hide_show_instance()

**Comment by pitbulk** [comment]
bradjones1, Can you review that?

**Comment by pitbulk** [comment]
Done:
9f6c30c7c5de430a1fc9aaa458e9c81abfb6f501
