### ISSUE TITLE
Fails to install into Moodle 3.0

### ISSUE THREAD

**Issue by Tracy-B** [pitbulk/moodle_saml#39]
When upgrading moodle to 3.0, the following error is returned:
Plugin "auth_saml" is defective or outdated, can not continue, sorry.

More information about this error
Debug info: Missing $plugin->component declaration in version.php.
Error code: detectedbrokenplugin
Stack trace:

    line 459 of \lib\upgradelib.php: plugin_defective_exception thrown
    line 1647 of \lib\upgradelib.php: call to upgrade_plugins()
    line 677 of \admin\index.php: call to upgrade_noncore()

**Comment by Tracy-B** [comment]
This was using version 'auth_saml_moodle29_2015072901' as published on the Moodle site https://moodle.org/plugins/auth_saml

**Comment by Tracy-B** [comment]
I've tried with the lasts version from github, and can confirm that nitro2010's change to version.php in https://github.com/pitbulk/moodle_saml/commit/31493f0599841936fd03654398c12febda6b061b fixed the problem.

**Comment by sestrauss** [comment]
Hello,

Can you tell me how you did the install? I tried to use the download file and then the "install plugin" option from the Admin GUI, but it did not seem to install--or even give an error message. It just told me that I need to select the plugin type, then tried to install, and never left the plugin page.

Thanks.

**Comment by Tracy-B** [comment]
Hi

I simply extracted the plugin into the folder moodle\auth\saml, then opened the ‘Site Administration’, ‘Notifications’ page.

Regards,

Mr Tracy Briscoe
Network Engineer

St Peter's School, Cambridge, Private Bag 884, Cambridge 3450, New Zealand
P +64 7 827 9899 ext 254  l  F +64 7 827 9812
www.stpeters.school.nz<http://www.stpeters.school.nz/>

**Comment by sestrauss** [comment]
OK. Thanks.

On Wed, Apr 6, 2016 at 4:44 PM, Tracy-B <notifications@github.com> wrote:

> Hi
>
> I simply extracted the plugin into the folder moodle\auth\saml, then
> opened the ‘Site Administration’, ‘Notifications’ page.
>
> Regards,
>
> Mr Tracy Briscoe
> Network Engineer
>
> St Peter's School, Cambridge, Private Bag 884, Cambridge 3450, New Zealand
> P +64 7 827 9899 ext 254 l F +64 7 827 9812
> www.stpeters.school.nz<http://www.stpeters.school.nz/>
>
>
>
> From: sestrauss [mailto:notifications@github.com]
> Sent: Thursday, 7 April 2016 3:27 a.m.
> To: pitbulk/moodle_saml <moodle_saml@noreply.github.com>
> Cc: Tracy Briscoe <Tracyb@stpeters.school.nz>
> Subject: Re: [pitbulk/moodle_saml] Fails to install into Moodle 3.0 (#39)
>
>
> Hello,
>
> Can you tell me how you did the install? I tried to use the download file
> and then the "install plugin" option from the Admin GUI, but it did not
> seem to install--or even give an error message. It just told me that I need
> to select the plugin type, then tried to install, and never left the plugin
> page.
>
> Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/pitbulk/moodle_saml/issues/39#issuecomment-206427618>
>
> Note: This communication may contain privileged and confidential
> information intended only for the addressee named above. Any views or
> opinions presented are solely those of the author. If you have received
> this message in error, we request you delete the message and notify the
> sender. Please do not distribute, copy or disclose any information. This
> e-mail has been scanned for viruses but all liability for viruses or
> similar in any attachment or message is excluded.
>
> St Peter's School, Cambridge, New Zealand
> Telephone: 647 827 9899 Fax: 647 827 9812
> Website: www.stpeters.school.nz<http://www.stpeters.school.nz/>
>
> Please consider the environment before printing this email
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/pitbulk/moodle_saml/issues/39#issuecomment-206558076>
>



-- 
Sharon Strauss
Instructional Technology Services
IITS
Haverford College <http://iits.haverford.edu>
sstrauss@haverford.edu
610-896-4916

IITS staff will never ask for your password.
The privacy of your password enhances the privacy of our entire community
and the integrity of our technology environment.
Check us out on the web - http://www.haverford.edu/iits
Read our blog -  http://iits.haverford.edu/instructionaltechnology/
