### ISSUE TITLE
Split the plugins into separate repos

### ISSUE THREAD

**Issue by juho-jaakkola** [pitbulk/moodle_saml#44]
Having the `auth_saml` and `enrol_saml` plugins in separate git repositories would allow installing them by cloning the git repository directly either to `auth/` or `enrol/` directory. This would make installing and testing much easier from developer's point of view.

See http://blogs.atlassian.com/2014/04/tear-apart-repository-git-way/

**Comment by bradjones1** [comment]
These are now at https://github.com/moodle-saml
