### ISSUE TITLE
Needs License

### ISSUE THREAD

**Issue by bradjones1** [pitbulk/moodle_saml#48]
Add a license?

**Comment by pitbulk** [comment]
The License is defined here:
* https://github.com/pitbulk/moodle_saml/blob/master/auth/saml/README.txt#L3
* https://github.com/pitbulk/moodle_saml/blob/master/enrol/saml/README.txt#L3

If you think is a good idea to create a LICENSE.md file, do it :)

**Comment by bradjones1** [comment]
I think we can just specify this inside the composer.json file, as well, and that should be sufficient.
