### ISSUE TITLE
Additional maintainers?

### ISSUE THREAD

**Issue by bradjones1** [pitbulk/moodle_saml#49]
Thanks for writing this helpful module! There are a few outstanding PR's and issues; would you be open to adding additional maintainers to help work through the backlog? (Yes, I'm volunteering.)

Thanks!

**Comment by pitbulk** [comment]
I sent you an invitation, once you think is a good time to do a release, we can schedule a meeting and do the official release on Moodle, after time, I have no problem adding you there and become a collaborator there too.

**Comment by bradjones1** [comment]
Added, and that all sounds good. Thanks.
