### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by bradjones1** [pitbulk/moodle_saml#51]
With so many people (apparently) depending on this module, and there being a few PR's and substantial issues pending, we should probably add a CI test process to the project.

Travis CI seems to be the most obvious choice. I don't have time to work on this just this second, so putting up this issue to see if there are any strong thoughts on another platform (e.g., CircleCI) before moving forward with Travis.

@pitbulk I'd probably need you to set up webhooks in the project settings when we make a move.

**Comment by pitbulk** [comment]
I'm using Travis at [php-saml toollkit](https://github.com/onelogin/php-saml/blob/master/.travis.yml) and I'm happy with it.

You can try to integrate Moodle's code style:
https://docs.moodle.org/dev/Coding_style

and we can try to add some unit test for some methods.

**Comment by bradjones1** [comment]
Well, that's why I'm trying to help. :smile: We all appreciate the work the contributors have put in.

**Comment by pitbulk** [comment]
any progress?

**Comment by bradjones1** [comment]
@pitbulk I've been off the project that uses Moodle for a few weeks but getting back on it this week, thanks for the nudge. First step will be to get Travis up and going with a simple install validation, I think.

**Comment by bradjones1** [comment]
@pitbulk I think you may need to set up the Travis integration since I don't have management permissions, and this project is on your personal namespace. Another option would be to create a moodle_saml organization and transfer the ownership there, and then I could help manage the organization. Up to you. Thanks.

**Comment by bradjones1** [comment]
Moved to
https://github.com/moodle-saml/enrol/issues/1
https://github.com/moodle-saml/auth/issues/1
