### ISSUE TITLE
Login Error Message is missing!

### ISSUE THREAD

**Issue by adjosh** [pitbulk/moodle_saml#52]
Hello,

We are in the process of setting up SAML integration with Shibboleth for our Moodle site and have installed the SAML plugin version 2015072901 on our development server (Moodle 2.8.6+ Build 20150521).
Our set up has one group of users authenticating with SAML and another population using manual accounts.

During testing we have noticed that if a user enters a wrong username or password for the manual login, there is no error message to inform the user what happened. (e.g. "Invalid username or password.") The page just reloads and presents the login page as though nothing happened.

Inspection of the login.php and index.php pages in the SAML plugin has revealed that there is no code handling display of error messages to the user if their log in fails.

Is there any chance this could be an easy and quick fix?
We need to deploy this solution the first week of August.

Thanks for your attention and help.

Best Regards,
Sarah Ashley.
Instructional Designer
Office of Instructional Technology and eLearning Solutions (ITeS)
RUTGERS/OIT
RSDM Bldg, Suite B725
110 Bergen St., Newark, NJ
Office: 973-972-8238
Cell: 973-289-7415
Email: ashleysa@oit.rutgers.edu
http://ites.rutgers.edu

**Comment by bradjones1** [comment]
> ...have installed the SAML plugin version 2015072901 on our development server (Moodle 2.8.6+ Build 20150521).

FYI, Moodle 2.8.x [went end-of-life](https://docs.moodle.org/dev/Releases#Moodle_2.8) in November 2015, and security updates are no longer provided for it, either. You're strongly encouraged to upgrade.

Since this is an open-source project, resolution of your issue depends on developer time being dedicated to validation and solution. There are a number of experienced PHP developers involved with this project, however if you are requiring a fix to your issue on a date certain, you might want to consider hiring someone to work through your issue. Otherwise, this issue will remain open and we will get to it in due course as availability permits. Thanks!

**Comment by adjosh** [comment]
Thanks for your response, Brad. Really appreciate it.
Plans to upgrade are underway for early next year but in the meantime this integration project has to be implemented. 
Can you recommend any PHP developer involved in this SAML project to whom we can reach out for hire?

Thanks again.

**Comment by bradjones1** [comment]
I'm certainly not pushing you to hire someone out of self-interest, it's just the nature of open source that a specific issue will usually get solved by someone who also has the same issue. So sometimes that doesn't line up with your schedule. I'll send you an e-mail. Also @pitbulk might have some ideas for you as the lead maintainer.

**Comment by adjosh** [comment]
Oh, no problem, Brad!
We are absolutely prepared to make it worth the while for whomever we can get to help us out from the team. We would rather hire someone who already knows the code and might find it easier to develop a solution quickly, if one doesn't already exist.

Thanks! Will look forward to your email.

**Comment by pitbulk** [comment]
@adjosh In the index.php there are several calls to [auth_saml_error](https://github.com/pitbulk/moodle_saml/blob/master/auth/saml/index.php#L80) that prompt SAML login errors.

I don't know when if you enable the double auth (normal and SAML) the normal auth is not showing the messages. Have you tried to change the priority order of the authentications?

**Comment by adjosh** [comment]
Thanks @pitbulk.

I apologize but I personally do not have the expertise to do that. Our Moodle Partner hosting vendor encouraged me to post the request/report the issue here, being the clients with the need for the issue to be resolved. They were talking of having to fork the code and look into fixing the problem and maintaining the modified code but don't have the human resources to work on that at the moment to serve our urgent need.

It's also why we are willing and ready to make it worthwhile for one you to help us fix whatever may be wrong.

If you are willing to direct me how to change the priority order of the authentications, i.e. on line X of index.php do ABC, I can certainly do that.

Thanks again for responding, both of you.

**Comment by pitbulk** [comment]
> They were talking of having to fork the code and look into fixing the problem and maintaining the modified code but don't have the human resources to work on that at the moment to serve our urgent need.

They could fork that github repository, fix the issue, create later a PR and thats all. This is how open source works and grow.

If they are not able to satisfy your needs maybe you selected a wrong hosting company.

> If you are willing to direct me how to change the priority order of the authentications, i.e. on line X of index.php do ABC, I can certainly do that.
Thats is done in the authentication UI: https://docs.moodle.org/31/en/Managing_authentication
But I don't know if that gonna solve your problem.

In my spare time I implemented and maintained several SAML plugins for free, but my personal situation changed and right now I'm busy with others tasks and is sad but I don't have enough time to maintain properly this moodle auth plugin (I asked for help [as you can see on the comments of the official website](https://moodle.org/plugins/auth_saml).

**Comment by adjosh** [comment]
Oh, I see! Changing the order of the authentication methods! I thought you were talking about something on the index.php page of the plugin. Sorry.
I tried that but still am not seeing any error messages displayed for wrong manual login. Thanks for the direction.
We are ready to pay you for your help, @pitbulk . Or even for hire you are unable to help?

Thanks for your contribution to Moodle! We appreciate all you developers making Moodle great!

**Comment by bradjones1** [comment]
See issue in new repo.
