### ISSUE TITLE
auto login bypass for known manual user?

### ISSUE THREAD

**Issue by jtsafran** [pitbulk/moodle_saml#53]
When auto login is enabled, is there a way to bypass this with a known manual username?  For example, with the CAS plugin, you can append the url as such: https://<moodle site>/login/index.php?username=SomeManualUser and bypass the CAS redirect.

**Comment by pitbulk** [comment]
This function doesn't exist on the SAML plugin.

**Comment by bradjones1** [comment]
@jtsafran Going to consider this a feature request; we're doing some repo cleanup so if you still want to pursue this, please file an issue against https://github.com/moodle-saml/auth
