### ISSUE TITLE
logout does not remove SimpleSAMLAuthToken cookie

### ISSUE THREAD

**Issue by dustinbrisebois** [pitbulk/moodle_saml#55]
should include something like this to remove the SAML Token process for logout, unfortunately adding this to the logout_hook won't work as the cookies recreate themselves as the user is not logged out yet.

unset($_COOKIE['SimpleSAMLAuthToken']);
setcookie('SimpleSAMLAuthToken', null, -1, '/');

**Comment by pitbulk** [comment]
This session name belong simpleSAMLphp so is that piece of software who need to remove that.
